language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
 - TRAVIS=true

matrix:
  fast_finish: true

before_install:
 - composer self-update || true
 - composer install --prefer-source --no-interaction

before_script:
  - phpenv config-rm xdebug.ini

script:
  - vendor/bin/phpunit --bootstrap tests/bootstrap.php --configuration tests/phpunit.xml
  - php vendor/bin/phpcs -n --standard=phpcs.xml --extensions=php src/ demo1 demo2 endpoints tests

after_script:
  - export TRAVIS=https://travis-ci.com/patrickallaert/php-saml
  - echo $TRAVIS
  - echo $TRAVIS_JOB_ID
